# Generated by Django 5.2.8 on 2025-11-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serviceprovider_farmerinsight_service_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='produce_description',
            field=models.TextField(blank=True, help_text="Short description of the farmer's produce", null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='seasonality',
            field=models.JSONField(blank=True, default=dict, help_text='JSON map of month->availability', null=True),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.market')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
