"""Add buyer profile description and transport fields

Generated by assistant to sync model changes to the database schema.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_farmerprofile_produce_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of buyer needs', null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='has_transport',
            field=models.BooleanField(default=False, help_text='Does the buyer have means of transport?'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='transport_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, help_text='Transport capacity in chosen unit'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='transport_unit',
            field=models.CharField(blank=True, default='kg', max_length=20),
        ),
    ]
