# Generated by Django 5.2.8 on 2025-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_buyerprofile_description_and_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text='List of product requests (JSON)', null=True),
        ),
    ]
