# Generated by Django 5.2.8 on 2025-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_buyerprofile_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
